Feature/Pages Refactoring
rabbithay/linkr pull request #26
Opened 2021-09-20 20:57 UTC by TiagoVota

Nesse refactoring pegamos as cinco páginas principais da nossa aplicação que são semelhantes (a de timeline, hashtags, my-posts, my-likes e someonesPosts) e fizemos uma refatoração delas.
Agora, ao invés de termos cinco arquivos que precisam ter todas as informações dos layouts, existem: só um componente geral (o MainPage.jsx, dentro da pasta 'shared'), que carrega todo o layout, e funcionalidades que a página tem que ter; e temos os cinco componentes das páginas anteriormente citadas, que agora são componentes mais enxutos e que passam para o componente MainPage as funcionalidades que ele precisa ter para com essa página!

2021-09-20 22:42 UTC, brunatb commented on src/pages/MyLikes/index.jsx
> +		<MainPage
A ideia é deixar o nome do componente esse mesmo?

2021-09-20 23:48 UTC, TiagoVota commented on src/pages/MyLikes/index.jsx
> +		<MainPage
Não. Boa!
Eu tinha colocado esses componentes porque esses de testes da refatoração e os antigos estava coexistindo, então para não dar problema com os nomes fiz essa diferença. Obrigado!

2021-09-21 00:09 UTC, TiagoVota commented on src/pages/MyLikes/index.jsx
> +		<MainPage
Arrumado!

2021-09-21 04:03 UTC, rabbithay requested changes

2021-09-21 04:03 UTC, rabbithay commented on src/pages/shared/MainPage.jsx
> +		// TODO: Não tem jeito melhor de deixar isso? Coloquei
separa em duas desestruturações?

2021-09-21 04:03 UTC, rabbithay commented on src/pages/shared/MainPage.jsx
> +						// TODO: Tirar esse if daqui. Achei ele meio bizarro, mas não pensei em nada
não dá pra fazer isso já ao entrar na página conferindo o useLocation?

2021-09-21 04:03 UTC, rabbithay commented on src/pages/shared/MainPage.jsx
> +	if (isSomeonesPage) {
inclusive, todas as ações que precisam ser feitas referentes apenas a um componente como nesse caso, dá pra deixar numa função fora desse componente, la no componente de origem e passar por props pra cá, sendo apenas chamada aqui dentro, caso esteja naquela rota específica

2021-09-21 04:03 UTC, rabbithay commented on src/pages/shared/MainPage.jsx
> +	if (isSomeonesPage) {
nao sei se ficou claro, parece confuso jasdhkajd

2021-09-21 14:21 UTC, TiagoVota commented on src/pages/shared/MainPage.jsx
> +		// TODO: Não tem jeito melhor de deixar isso? Coloquei
Pode ser, eu tinha até feito, só tinha achado 'feio' esteticamente, porém acho que é uma ideia melhor né, que daí temos certeza que não pode dar qualquer problema com as outras variáveis constantes

2021-09-21 14:22 UTC, TiagoVota commented on src/pages/shared/MainPage.jsx
> +						// TODO: Tirar esse if daqui. Achei ele meio bizarro, mas não pensei em nada
Nem ideia, nunca usei o useLocation, porém sou bem aberto para descobrir hehehehe

2021-09-21 14:30 UTC, TiagoVota commented on src/pages/shared/MainPage.jsx
> +	if (isSomeonesPage) {
Entendi, acho sensato, porém eu não soube muito como aplicar aqui, porque dentro do if do (isSomeonesPage) temos duas coisas: a de verificar se a página é do próprio usuário (que até daria para fazer no componente do SomeonesPage (dando um userContext e pegando o params).
Porém ali precisa pegar o nome do usuário. E isso me deixou meio bugado, porque o jeito de fazer isso é fazendo a requisição dos Posts e pegando o userName de dentro de um esses posts (que inclusive eu acho que daria BO se a pessoa não tiver nenhum Post (spoilers de problemas para resolvermos para os próximos capítulos).

2021-09-21 17:29 UTC, rabbithay commented on src/pages/shared/MainPage.jsx
> +						// TODO: Tirar esse if daqui. Achei ele meio bizarro, mas não pensei em nada
com o useLocation().pathname vc consegue pegar o nome da rota que vc está

2021-09-21 23:36 UTC, rabbithay approved these changes

2021-09-21 23:36 UTC, rabbithay commented on src/pages/shared/MainPage.jsx
> +	if (isSomeonesPage) {
verdade, nesse caso, nao poderia usar a função ate estar com essas informações, que seria quando recebesse o retorno da requisição, mas ela poderia ja estar declarada fora e recebida por props. mas de fato, acho que o if vai ter que acontecer pra isso de qualquer forma dentro do then mesmo... hm..... MAS kkkkk a outra parte é bom que aconteça no inicio da pagina, pq caso esteja na rota do proprio user, nao precisa fazer duas requisições, ja entra e é dado push direto pro my-posts. o que vc acha? faz sentido?

2021-09-21 23:38 UTC, rabbithay approved these changes
MUITO BOMMMMMMMM !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2021-09-22 12:00 UTC, brunatb commented on src/pages/SomeonesPosts/index.jsx
> +				.catch(({ response }) => console.log(response));
Acho que vale a pena trocar o console log por algo mais informativo para o usuário.

2021-09-22 13:54 UTC, merged